[package]
name = "study-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
hmac = "0.12.1"
hex = "0.4.3"

[[example]]
name = "study_hmac"
path = "examples/study_hmac.rs"